---
files: .
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-ast

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks:
  - id: bandit
    args: [--recursive, -lll, -iii]

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
    language_version: python3
    args: [--config, ./pyproject.toml]
