line-length = 119
extend = "./pyproject.toml"
[lint]
select = ["E", "F", "UP", "I"]
extend-ignore = ["E203"]
ignore = [
#  "WPS305", # Found `f` string
  "D100", # Missing docstring in public module
  "D105", # Missing docstring in magic method
  "D107", # Missing docstring in __init__
#  "WPS412", # Found `__init__.py` module with logic
#  "WPS306", # Found class without a base class
  "D106", # Missing docstring in public nested class
  "D401", # First line should be in imperative mood
#  "WPS110", # Found wrong variable name
#  "WPS326", # Found `__init__.py` module with logic
#  "WPS226", # Found string constant over-use
#  "WPS115", # Found upper-case constant in a class
#  "WPS602", # Found nested function
#  "WPS605", # Found method without arguments
#  "WPS204", # Found overused expressio
#  "WPS202", # Found too many module members
#  "WPS232", # Found too high module cognitive complexit
#  "W503", # line break before binary operator
#  "WPS201", # Found module with too many imports
#  "RST210", # Inline strong start-string without end-string
#  "WPS431", # Found nested class
#  "WPS100", # Found wrong module name
#  "WPS214", # Found too many methods
#  "WPS229", # Found too long ``try`` body
#  "WPS615", # Found unpythonic getter or setter
#  "WPS348", # Found a line that starts with a dot
#  "WPS404", # Found complex default value (for dependency injection)
  "B008", #  not perform function calls in argument defaults (for dependency injection)
#  "DJ10", # Model should define verbose_name in its Meta inner class
#  "DJ11", # Model should define verbose_name_plural in its Meta inner class
#  "WPS407", # Found mutable module constant.
#  "WPS473", # Found too many empty lines in `def`
#  "PIE781", # Чтобы можно было задать переменную на одной строчке, а потом прописать ее в return. Иногда так удобней.
]
exclude = [
  "./.cache",
  "./.git",
  "./.idea",
  "./.mypy_cache",
  "./.pytest_cache",
  "./.venv",
  "./venv",
  "./env",
  "./cached_venv",
  "./docs",
  "./deploy",
  "./var",
  "./.vscode",
  "*migrations*",
  "*env.py",
  "etup.py",
  "*gunicorn.py",
]


[lint.per-file-ignores]
  # all tests
  "*/conftest.py" = [
    "S101", # Use of assert detected
#    "WPS442", # Found outer scope names shadowing
#    "WPS210", # Found too many local variables
#    "WPS432", # Found magic number
#    "DAR101", # Missing parameter(s) in Docstring
#    "WPS211", # Found too many arguments
  ]

  # all init files
  "*/__init__.py" = [
    "F401", # ignore not used imports
    "F403", # ignore import with wildcard
#    "WPS410", # Found wrong metadata variable
  ]

  # variable names that shadow builtins are not allowed in all models
#  "src/example_app/models/*" = ["VNE003"]
#  "*/models.py" = ["VNE003"]


[lint.isort]
force-single-line = true


[lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 8.
max-complexity = 8


[lint.flake8-quotes]
inline-quotes = "double"
